### ISSUE TITLE
Possible Issue with Backrooms Integration

### ISSUE THREAD

**Issue by DarianLStephens** [Tigereye504/chestcavity#13]
This could just be terrible luck, but after searching dozens of chests in each level, I've never found a single organ; only the regular loot defined in the loottables.
I don't know how to look in to this further, so I'm leaving this here in the hopes that you can figure out what might be wrong, if anything, because going in to the backrooms to get good quality organs instead of having to harvest them from humans or villager seems like an interesting way to go.

**Comment by DarianLStephens** [comment]
Ah, it seems I _did_ just have bad luck! Either that, or the organs are insanely rare, because I finally just found something on level 0!
![2021-02-27_06 59 15](https://user-images.githubusercontent.com/15375876/109349059-757fc700-78c9-11eb-9937-ef9306c116e5.png)

**Comment by Tigereye504** [comment]
I'll take a look at the spawn rate, see if it needs tweaked. Maybe add a config, that sort of thing can always use one

**Comment by Tigereye504** [comment]
yea, the drop rate was too low for how common the chests are. I've increased the odds to have organs in roughly 19% of chests, and added some config options to the integration tab for further tweaking.

The changes will be in the next update
