### ISSUE TITLE
Forge integration 

### ISSUE THREAD

**Issue by BJSanford** [Tigereye504/chestcavity#16]
Can you integrate this into forge I’m making a mod pack that has been highly requested which is a random mods mod pack so I found this and thought this would be perfect but found out it was for fabric could you make it for forge and also for 1.12.2 it would help a lot

**Comment by Tigereye504** [comment]
Sorry, but that far back and across mod frameworks is quite the tall order. Forge integration isn't gonna happen any time soon.
