### ISSUE TITLE
cant open other players

### ISSUE THREAD

**Issue by WillHam** [Tigereye504/chestcavity#28]
ive done server config made it able to open players, but it opens my chest cavity instead of the other players.
it opens their chest cavity for a second then it opens mine

**Comment by WillHam** [comment]
"ORGAN_BUNDLE_LOOTING_BOOST": 0.01,
  "UNIVERSAL_DONOR_RATE": 0.035,
  "ORGAN_REJECTION_DAMAGE": 0,
  "ORGAN_REJECTION_RATE": 600,
  "HEARTBLEED_RATE": 20,
  "KIDNEY_RATE": 60,
  "FILTRATION_DURATION_FACTOR": 1.0,
  "APPENDIX_LUCK": 0.1,
  "HEART_HP": 4.0,
  "MUSCLE_STRENGTH": 1.0,
  "MUSCLE_SPEED": 0.5,
  "BONE_DEFENSE": 0.5,
  "RISK_OF_PRIONS": 0.01,
  "CHEST_OPENER_ABSOLUTE_HEALTH_THRESHOLD": 20,
  "CHEST_OPENER_FRACTIONAL_HEALTH_THRESHOLD": 0.5,
  "CAN_OPEN_OTHER_PLAYERS": true,
  "KEEP_CHEST_CAVITY": true,
  "DISABLE_ORGAN_REJECTION": true,
  "ARROW_DODGE_DISTANCE": 32,
  "BUFF_PURGING_DURATION_FACTOR": 0.5,
  "CRYSTALSYNTHESIS_RANGE": 32,
  "CRYSTALSYNTHESIS_FREQUENCY": 10,
  "FIREPROOF_DEFENSE": 0.75,
  "IMPACT_DEFENSE": 0.75,
  "LAUNCHING_POWER": 0.1,
  "MAX_TELEPORT_ATTEMPTS": 5,
  "RUMINATION_TIME": 400,
  "RUMINATION_GRASS_PER_SQUARE": 2,
  "RUMINATION_SQUARES_PER_STOMACH": 3,
  "SHULKER_BULLET_TARGETING_RANGE": 20,
  "SWIMSPEED_FACTOR": 1.0,
  "WITHERED_DURATION_FACTOR": 0.5,
  "ARROW_DODGE_COOLDOWN": 200,
  "DRAGON_BOMB_COOLDOWN": 200,
  "DRAGON_BREATH_COOLDOWN": 200,
  "EXPLOSION_COOLDOWN": 200,
  "FORCEFUL_SPIT_COOLDOWN": 20,
  "GHASTLY_COOLDOWN": 60,
  "PYROMANCY_COOLDOWN": 78,
  "SHULKER_BULLET_COOLDOWN": 100,
  "SILK_COOLDOWN": 20,
  "VENOM_COOLDOWN": 40,
  "AGE_OF_EXILE_INTEGRATION": true,
  "ANTHROPOPHAGY_INTEGRATION": true,
  "BACKROOMS_INTEGRATION": true,
  "BACKROOMS_CHEST_ORGAN_LOOT_ATTEMPTS": 2,
  "BACKROOMS_CHEST_ORGAN_LOOT_CHANCE": 0.2,
  "BEWITCHMENT_INTEGRATION": true,
  "BIOME_MAKEOVER_INTEGRATION": true,
  "CREEPER_SPORES_INTEGRATION": true,
  "DIREBATS_INTEGRATION": true,
  "RATS_MISCHIEF_INTEGRATION": true,
  "REQUIEM_INTEGRATION": true,
  "SMALL_ENDERMEN_INTEGRATION": true,
  "SNOW_MERCY_INTEGRATION": true
}
this is the server config file

**Comment by A5TR0spud** [comment]
seems like you did it for the server, but do all clients involved have it on too?
