### ISSUE TITLE
Inventory Offset

### ISSUE THREAD

**Issue by DarianLStephens** [Tigereye504/chestcavity#29]
When opening the Chest Cavity, your inventory slots are a few pixels offset from where they should be.
The Chest Cavity inventory itself is properly-aligned, but the lower, player inventory is not.

This isn't a major issue, but it's something I've noticed for a few versions now, and is hard to ignore once you see it.

Chest Cavity:
![2021-04-13_15 15 26](https://user-images.githubusercontent.com/15375876/114500326-228c8400-9c6b-11eb-91d7-42209b3a2143.png)

Regular Inventory:
![2021-04-13_15 15 32](https://user-images.githubusercontent.com/15375876/114500345-29b39200-9c6b-11eb-94fb-36582bf93a57.png)

**Comment by A5TR0spud** [comment]
oh, weird

**Comment by A5TR0spud** [comment]
heh the 1.17 version of cc fixes this but now the chest cavity is offset

**Comment by Tigereye504** [comment]
Should be fixed in latest version
