### ISSUE TITLE
Can't open EnderChests

### ISSUE THREAD

**Issue by TinglyRobin3014** [Tigereye504/chestcavity#30]
Any time I try to open an Enderman's chest or the dragon's chest, it doesn't let me

**Comment by A5TR0spud** [comment]
in the newest version, if a mob has more than 10 hearts and is over half health you cant open them. this is to prevent you from skipping a fight by removing vital organs

**Comment by Suitov** [comment]
I actually like this. It'd feel anticlimactic to kill the dragon by popping out her heart.

I have noticed that all you-can't-open-this-mob's-chest sounds are subtitled as "turtle shell thunks", but that's minor. I soon worked out what it means.

**Comment by Tigereye504** [comment]
As A5tro said, this is not a bug.
