### ISSUE TITLE
hydrophobia

### ISSUE THREAD

**Issue by IcySho** [Tigereye504/chestcavity#34]
i don't know if its just me but if i touch water with the ender kidney i am teleported until death and it doesn' stop untill i take it out, i like the hydrophobia idea but the fact i teleport till death makes it unusable but again i don't know if its just me or not

**Comment by Tigereye504** [comment]
I am unable to replicate this issue. While it often takes several jumps before I land somewhere dry (the teleport is random after all), the only times I have been unable to escape water are situations where there is very little place one could escape to such as superflat worlds in the rain or the middle of the ocean.
