### ISSUE TITLE
add data driven organs

### ISSUE THREAD

**Issue by Nathan22211** [Tigereye504/chestcavity#5]
this would make custom organs easier to make than with code. below is an example syntax I came up with for Xenomorpth muscle (I have an idea for a mod like that on the brain, don't judge)

{
    "item": "aliens:xenomrpth_muscle", // the item that's the organ
    "nbt": "{Type:"Drone"}", // the NBT of the item. Useful for datapack makers. Also, I have no clue if the strengths differ by type, I needed something to show NBT off.
    "attributes": [  //attributes applied to the player. The number will represent the amount a full-stack gives
        "generic_attackDamage": 0.25,
        "generic_movementSpeed": 0.000003, // movement speed has really random numbers, and I don't know the one of the player
        ]
    "effects": [  //potion effects given to the player. makes interactions with some mods easier.
        {
            "id": "vrm:poisonresisteffect",
            "amplifier": 1,
            "logic": "full" //determines how the effect is computed. "full" will require the full stack for the effect. "split" will apply a less amplified effect if a percentage of the stack is there. stack/amplifier i.e. 32 of the item will only apply the effect with an amplifier of 0. if it's not a whole number it'll round up.
            "amount": [ //determines how much is needed for the effect to begin. if it's set to  "split", it'll be this amount for the base amplifier and require double for the next amplifier. If set to "full" it'll require this amount
                "count": 2,
                "logic": "stack" //takes "stack" or "count". Count takes 2 of the item. and "stack takes 2 stacks.
        }
    ]
    "functions": [ //the functions that are run as the player and at their location. makes compatibility with datapacks easier.
    {
        "path": "aliens:aliens/fire_fear", //function path, takes tags too
        "delay": 5, //delay in ticks of the function being run
       }
    ]
}

Sorry if it's long, there's a lot I factored in, and yet there's one thing I know I'm missing, the Xenomorphs vulnerability to fire, but I'm not sure how that could be implemented.

**Comment by Tigereye504** [comment]
Complete at long, long last!
