### ISSUE TITLE
Multiplayer

### ISSUE THREAD

**Issue by Fiiiiiiiiish** [Tigereye504/chestcavity#51]
Is it possible to gain access to the chest cavity of other players on my server? We added the mod but I only can open mine

**Comment by Fiiiiiiiiish** [comment]
found it on the discord faq!

**Comment by Problemreported** [comment]
then what is it? Im not on discord

**Comment by Tigereye504** [comment]
In the configuration file, set CAN_OPEN_OTHER_PLAYERS to true on both the
server and the clients. I don't recommend doing so, however, as it is very
easy to grief people with that setting enabled.
