### ISSUE TITLE
Crash on startup with chestcavity | Possible incompatibility

### ISSUE THREAD

**Issue by KavisKryptic** [Tigereye504/chestcavity#55]
[Disclaimer, I put this in the discord, but I thought I might as well put it in here also]

Minecraft 1.17.1

Fabric (API 0.41.0) ~ I'm making a modpack and chest cavity (2.13.0) causes a crash on startup. Removing the mod fixes the issue entirely.

Pastebin for the log [here](https://pastebin.com/bPrumfrk)

**Comment by DarianLStephens** [comment]
I have the same issue. It seems like an incompatibility with Origins, because removing either mod solves the water travel mixin crash.

**Comment by Tigereye504** [comment]
Origins incompatibility has been resolved; closing issue.
