### ISSUE TITLE
Botania mixin conflict

### ISSUE THREAD

**Issue by AeiouEnigma** [Tigereye504/chestcavity#56]
[latest.log](https://pastebin.com/nGeLt8E8)

Installing both Botania (Fabric) and Chest Cavity results in a crash upon loading a world. Botania's MixinLootTable class targets the filterDisposables method which Chest Cavity's ([modify-drops-api](https://github.com/Tigereye504/modify-drops-api/blob/857d48689334239b000ba060812062bff66e75ec/src/main/java/net/tigereye/modifydropsapi/mixin/LootTableGenerateLootMixin.java#L18)'s?) LootTableGenerateLootMixin class modifies.

Hopefully a solution can be found.

**Comment by Dustalis** [comment]
I'm experiencing the same issue on world load.
[crash-2021-12-07_00.13.06-client.txt](https://github.com/Tigereye504/chestcavity/files/7665930/crash-2021-12-07_00.13.06-client.txt)

**Comment by Tigereye504** [comment]
Fixed in 2.13.5
