### ISSUE TITLE
random crashlog for ya

### ISSUE THREAD

**Issue by ItsBonezey** [Tigereye504/chestcavity#6]
[crash-2020-10-21_01.39.08-server.txt](https://github.com/Tigereye504/chestcavity/files/5414483/crash-2020-10-21_01.39.08-server.txt)
wish I could be more helpful than this, but it crashes the game whenever I die with the mod. it didn't always do this, but as soon as I dinked around with "Age Of Exile" this happens. deleted the mods I added and... it still happens. I'll try running it on it's own (and with origins) in a while. but I thought I'd pass this over. from what I can read, it's related to the "inventory" changes on death. when it checks for the essential organs and replaces them, maybe?

**Comment by ItsBonezey** [comment]
it's bloody curios.

**Comment by Tigereye504** [comment]
Sorry for taking so long to respond, but based on the crash log this is related to cardinal components's experimental player components, which I have stopped using in the latest update.
