### ISSUE TITLE
Anthropophagy Compat

### ISSUE THREAD

**Issue by Nahere** [Tigereye504/chestcavity#88]
Minecraft 1.19.2
Quilt 0.18.1-beta.21
Chest Cavity 2.16.3
Anthropophagy 1.19.2
Pigluttons have chests full of dirt as opposed to actual organs. This is possibly due to the fact that 'anthropophagy' is misspelled as 'antropophagy' in both '/src/main/resources/data/' and '/src/main/resources/data/chestcavity/entity_assignment/compatibility/'.

**Comment by Tigereye504** [comment]
fixed in latest version, the issue was the typo
