### ISSUE TITLE
game crashing when im loading the mod

### ISSUE THREAD

**Issue by idozwi** [Tigereye504/chestcavity#92]
when i load the mod and launch the game the game gives me this error:
https://pastebin.com/gZmcSamU

**Comment by idozwi** [comment]
fixed it

**Comment by DarianLStephens** [comment]
If you can, don't just say 'fixed it', give some details.
It's bound to help out someone in the future with the same issue.

**Comment by Tigereye504** [comment]
He had forgotten to install Cloth Config

**Comment by idozwi** [comment]
okay sorry the problem was that I installed an older version of the cloth config mod. Hope it helped
