### ISSUE TITLE
How do I make an organ safe to use?

### ISSUE THREAD

**Issue by zurgeg** [Tigereye504/chestcavity#96]
Tried transplanting a suspiciously large amount of muscles into a villager from another villager and he died of organ rejection.

**Comment by Tigereye504** [comment]
You don't make compatible organs, you find them. Any organ that drops as
loot from a mob will be safe to use. You can improve the odds of organ
drops with the Looting or Surgical enchantments, with Surgical being twice
as effective but only for organ drops.

**Comment by zurgeg** [comment]
> Wasn't there a treasure enchantment you could apply to organs that would _make_ them compatible, or am I mistaken?

O Negative is an enchantment, I don't know what it does, but O- blood type can handle blood from anyone, so that might have something to do with it.

**Comment by FalIen-Angel** [comment]
> You don't make compatible organs, you find them. Any organ that drops as
> loot from a mob will be safe to use. You can improve the odds of organ
> drops with the Looting or Surgical enchantments, with Surgical being twice
> as effective but only for organ drops.
> […](#)

Hello, What to do if organs don't drop even with enchantments?
